apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: monitoring-service
    spec:
      containers:
        - name: monitoring
          image: thegaijin/monitoring
          ports:
            - name: port1
              containerPort: 8989
            - name: port2
              containerPort: 8080
