---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: monitoring-service
  ports:
    - port: 8989
      protocol: TCP
      targetPort: 8989