apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-ms-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: account-service
    spec:
      containers:
        - name: ms-pgs-account-service
          image: thegaijin/ms-pgs-account-service
          ports:
            - containerPort: 6000
        - name: ms-pgs-account-mongodb
          image: thegaijin/ms-pgs-account-mongodb
          ports:
            - containerPort: 27017
          env:
            - name: ACCOUNT_SERVICE_PASSWORD
              value: ${ACCOUNT_SERVICE_PASSWORD}
            - name: CONFIG_SERVICE_PASSWORD
              value: ${CONFIG_SERVICE_PASSWORD}
            - name: MONGODB_PASSWORD
              value: ${MONGODB_PASSWORD}
