---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: account-service
  ports:
    - name: port1
      port: 6000
      protocol: TCP
      targetPort: 6000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
