version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    build: config/.
    container_name: ms-pgs-config
    image: thegaijin/ms-pgs-config:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    build: registry/.
    container_name: ms-pgs-registry
    image: thegaijin/ms-pgs-registry:latest
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    build: ./gateway
    container_name: ms-pgs-gateway
    image: thegaijin/ms-pgs-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: auth-service/.
    container_name: ms-pgs-auth-service
    image: thegaijin/ms-pgs-auth-service:latest
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    build: mongodb/.
    container_name: ms-pgs-auth-mongodb
    image: thegaijin/ms-pgs-auth-mongodb:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      ACCOUNT_SERVICE_PASSWORD: ${ACCOUNT_SERVICE_PASSWORD}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    build: account-service/.
    container_name: ms-pgs-account-service
    image: thegaijin/ms-pgs-account-service:latest
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: mongodb/.
    container_name: ms-pgs-account-mongodb
    image: thegaijin/ms-pgs-account-mongodb:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
    build: statistics-service/.
    container_name: ms-pgs-statistics-service
    image: thegaijin/ms-pgs-statistics-service:latest
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: mongodb/.
    container_name: ms-pgs-statistics-mongodb
    image: thegaijin/ms-pgs-statistics-mongodb:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    build: notification-service/.
    container_name: ms-pgs-notification-service
    image: thegaijin/ms-pgs-notification-service:latest
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    build: mongodb/.
    container_name: ms-pgs-notification-mongodb
    image: thegaijin/ms-pgs-notification-mongodb:latest
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: ./monitoring
    container_name: ms-pgs-monitoring
    image: thegaijin/ms-pgs-monitoring
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
