---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: auth-service
  ports:
    - name: port1
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
