---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-ms-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: auth-service
    spec:
      containers:
        - name: ms-pgs-auth-service
          image: thegaijin/ms-pgs-auth-service
          ports:
          - containerPort: 5000
            protocol: TCP
        - name: ms-pgs-auth-mongodb
          image: thegaijin/ms-pgs-auth-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
            - name: ACCOUNT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: STATISTICS_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: NOTIFICATION_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
