---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-ms-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: notification-service
    spec:
      containers:
        - name: ms-pgs-notification-service
          image: thegaijin/ms-pgs-notification-service
          ports:
          - containerPort: 8000
            protocol: TCP
        - name: ms-pgs-notification-mongodb
          image: thegaijin/ms-pgs-notification-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
            - name: NOTIFICATION_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
