---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: notification-service
  ports:
    - name: port1
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
  type: NodePort
