apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-ms-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: notification-service
    spec:
      containers:
        - name: ms-pgs-notification-service
          image: thegaijin/ms-pgs-notification-service
          ports:
            - containerPort: 8000
          env:
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: ${NOTIFICATION_SERVICE_PASSWORD}
            - name: MONGODB_PASSWORD
              value: ${MONGODB_PASSWORD}
