apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: config-service
    spec:
      containers:
        - name: config
          image: thegaijin/config
          ports:
            - containerPort: 8888
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: ${CONFIG_SERVICE_PASSWORD}
