---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: config-service
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
