---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: pgs-acc
spec:
  selector:
    app: pgs-acc
  ports:
    - name: port1
      port: 6000
      protocol: TCP
      targetPort: 6000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-ms-deployment
  labels:
    run: pgs-acc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: pgs-acc
    spec:
      containers:
        - name: ms-pgs-account-service
          image: thegaijin/ms-pgs-account-service
          ports:
          - containerPort: 6000
            protocol: TCP
        - name: ms-pgs-account-mongodb
          image: thegaijin/ms-pgs-account-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
            - name: ACCOUNT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
