---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: config
spec:
  selector:
    app: config
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
  labels:
    run: config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: config
    spec:
      containers:
        - name: config
          image: thegaijin/config
          ports:
          - containerPort: 8888
            protocol: TCP
          env:
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password