---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  type: NodePort


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  labels:
    run: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
        - name: gateway
          image: thegaijin/gateway
          ports:
          - containerPort: 4000
            protocol: TCP
          env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-credentials
                key: password