---
apiVersion: v1
kind: Service
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  selector:
    app: monitoring
  ports:
    - port: 8989
      protocol: TCP
      targetPort: 8989
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring
  labels:
    run: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: monitoring
    spec:
      containers:
        - name: monitoring
          image: thegaijin/monitoring
          ports:
          - name: port1
            containerPort: 8989
            protocol: TCP
          - name: port2
            containerPort: 8080
            protocol: TCP
      env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-credentials
              key: username