---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: pgs-notify
spec:
  selector:
    app: pgs-notify
  ports:
    - name: port1
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-ms-deployment
  labels:
    run: pgs-notify
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: pgs-notify
    spec:
      containers:
        - name: ms-pgs-notification-service
          image: thegaijin/ms-pgs-notification-service
          ports:
          - containerPort: 8000
            protocol: TCP
        - name: ms-pgs-notification-mongodb
          image: thegaijin/ms-pgs-notification-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
            - name: NOTIFICATION_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
