---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    run: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
        - name: rabbitmq:3-management
          image: rabbitmq:3-management
          ports:
          - containerPort: 15672
            protocol: TCP