---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    run: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
        - name: registry
          image: thegaijin/registry
          ports:
          - containerPort: 8761
            protocol: TCP