---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  labels:
    app: pgs-stat
spec:
  selector:
    app: pgs-stat
  ports:
    - name: port1
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
  type: NodePort


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-ms-deployment
  labels:
    run: pgs-stat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: pgs-stat
    spec:
      containers:
        - name: ms-pgs-statistics-service
          image: thegaijin/ms-pgs-statistics-service
          ports:
          - containerPort: 7000
            protocol: TCP
        - name: ms-pgs-statistics-mongodb
          image: thegaijin/ms-pgs-statistics-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
            - name: STATISTICS_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-credentials
                  key: password
