apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    run: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
        - name: registry
          image: thegaijin/ms-pgs-registry
          ports:
            - containerPort: 8761
