---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: registry-service
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
