apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: gateway-service
    spec:
      containers:
        - name: gateway
          image: thegaijin/ms-pgs-gateway
          ports:
            - containerPort: 4000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: ${CONFIG_SERVICE_PASSWORD}
