apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: gateway-service
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
