apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: rabbitmq-service
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq/3.7-management
          ports:
            - containerPort: 15672
