---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: rabbitmq-service
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
