---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: rabbitmq-service
    spec:
      containers:
        - name: rabbitmq:3-management
          image: rabbitmq:3-management
          ports:
          - containerPort: 15672
            protocol: TCP