- name: setup Jenkins master instance
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add jenkins key to the system, once the key is added, the system returns OK
      shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -

    - name: Add Jenkins debian repository address to the server's sources.list
      shell: |
              sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update the package list to pick up the new repository
      apt:
        update_cache: yes

    - name: install Jenkins and its dependencies
      apt:
        name:
          - jenkins
          - docker.io
          - tree
          - nginx
          - supervisor
          - unzip
          - wget
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        force: True
        owner: "root"
        group: "root"
        mode: "0755"

    - name: install terraform
      shell: |
              wget https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip
              unzip terraform_0.11.1_linux_amd64.zip -d terraform
              mv terraform /usr/local/bin/

    - name: Install Packer
      shell: |
              wget https://releases.hashicorp.com/packer/0.12.0/packer_0.12.0_linux_amd64.zip
              unzip packer_0.12.0_linux_amd64.zip -d packer
              mv packer /usr/local/
              export PATH="$PATH:/usr/local/packer"

    - name: configure jenkins user to access docker
      shell: |
              usermod -aG docker ubuntu
              usermod -aG docker jenkins

    - name: check if file has a symbolic link
      stat:
        path: /etc/nginx/sites-enabled/default
      register: app_file_symlink

    - name: create symlink if it doesnt exist
      file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link force=true
      when: app_file_symlink.stat.islnk is defined and app_file_symlink.stat.islnk == False
      become: yes
      become_method: sudo

    - name: write app rule
      shell: |
              bash -c 'cat > /etc/nginx/sites-available/default <<EOF
              server {
                      server_name jenkins.lenken.thegaijin.xyz;
                      location / {
                              proxy_pass http://127.0.0.1:8080;
                      }
              }
              EOF'

    - name: restart nginx
      shell: /etc/init.d/nginx restart

    - name: start jenkins
      shell: systemctl start jenkins

    - name: Jenkins runs on port 8080, so we'll open that port using ufw
      shell: ufw allow 8080

    - name: enable OpenSSH
      shell: ufw allow OpenSSH

    - name: generate ssh key
      shell: ssh-keygen -t rsa -N "" -f "/home/ubuntu/.ssh/id_rsa"

    - name: update cache || equivalent of sudo apt-get update
      apt:
        update_cache: yes

    - name: set up
      shell: apt-get -y install software-properties-common

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson