apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-ms-deployment
  labels:
    app: piggymetrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piggymetrics
        service: statistics-service
    spec:
      containers:
        - name: ms-pgs-statistics-service
          image: thegaijin/ms-pgs-statistics-service
          ports:
            - containerPort: 7000
          env:
            - name: STATISTICS_SERVICE_PASSWORD
              value: ${STATISTICS_SERVICE_PASSWORD}
            - name: MONGODB_PASSWORD
              value: ${MONGODB_PASSWORD}
