---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  labels:
    app: piggymetrics
spec:
  selector:
    service: statistics-service
  ports:
    - name: port1
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: port2
      port: 27017
      protocol: TCP
      targetPort: 27017
